# Site
repository: WhalesJin/WhalesJin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 서혜진
title: 호기심을 해결하는 iOS 개발자 서혜진입니다.
email: whales.w.jin@gmail.com
website: https://github.com/WhalesJin

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  WhalesJin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "2048: Number Sliding"
        link: https://apps.apple.com/kr/app/2048-number-sliding/id6497949242
        link_text: AppStore
        caption: 2023.10 - 2024.04
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            
            <br><br>
          
            **What i did**<br>
            
            <br><br>
            
            **Spec Sheet**<br>
            <mark>Swift</mark> <mark>UIKit</mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-1" aria-expanded="false" aria-controls="collapse-1" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-1">
            <ul>
              <li> </li>
            </ul>
            </div>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:
        additional_links:
          - title:
            icon: fab fa-github
            url:
        sub_title:
        caption:
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            
            <br><br>
            
            **What i did**<br>
            
            <br><br>
            
            **Spec Sheet**<br>
            <mark></mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-2" aria-expanded="false" aria-controls="collapse-2" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-2">
            <ul>
              <li>  </li>
            </ul>
            </div>
                
      - layout: left
        title:
        additional_links:
          - title:
            icon: fab fa-github
            url:
        sub_title:
        caption:
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            
            <br><br>
            
            **What i did**<br>
            
            <br><br>
            
            **Spec Sheet**<br>
            <mark></mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-2" aria-expanded="false" aria-controls="collapse-2" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-2">
            <ul>
              <li>  </li>
            </ul>
            </div>
            
            
            
#  - title: Other # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title:
#        caption:
#        sub_title:
#        description: | # this will include new lines to allow paragraphs
            
    

# Footer
footer_show_references: false
# references_title:

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
