# Site
repository: WhalesJin/WhalesJin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 서혜진
title: 호기심을 해결하는 iOS 개발자 서혜진입니다.
email: whales.w.jin@gmail.com
website: https://github.com/WhalesJin

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  WhalesJin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "2048: Number Sliding"
        link: https://apps.apple.com/kr/app/2048-number-sliding/id6497949242
        link_text: AppStore
        caption: 2023.10 - 2024.04
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            같은 숫자를 매칭시켜 더 큰 숫자를 만들어보세요! 목표 점수 2048!<br>
            단, 블럭 합성은 세로만 가능합니다.<br>
            (이벤트 블록이 포함되어 있습니다. 첫 화면에서 이벤트 블록의 종류를 선택하세요.)
            <br><br>
          
            **What I did**<br>
            - 해커톤의 조건인 ‘하나의 화면으로 구성된 게임’에 맞도록 게임 기획
            - 협업을 위한 그라운드 룰과 README 작성 리드
            - 게임 보드 화면과 애니메이션을 위한 좌표 계산 및 AutoLayout을 사용하여 다양한 크기의 화면 대응
            - 현재 최고 점수를 보여주는 Best Score UI 및 로직 구현
            - 블럭의 합성이 연쇄적으로 이루어지도록 게임 로직 수정
            - 앱 출시를 위한 이벤트 블록 기획 및 구현
            <br><br>
            
            **Spec Sheet**<br>
            <mark>Swift</mark> <mark>UIKit</mark> <mark>MVC</mark> <mark>CoreAnimation</mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-1" aria-expanded="false" aria-controls="collapse-1" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-1">
            <ul>
              <li> 게임 보드 화면과 애니메이션 구현 시 좌표로 인해 난항을 겪을 거라 주저하는 팀원들을 설득하기 위해 직접 좌표 계산을 했습니다. <strong>적당한 크기로 블록을 설정하고 등차수열을 활용하여 일정한 간격을 기준으로 가로와 세로의 좌표를 그리고 코드로 구현하였습니다.</strong> 해커톤 당시에는 아이폰 12라는 제한이 있어서 직접적인 숫자로 넣었지만 앱 출시 전에 다양한 크기의 디바이스에 대응하기 위해 <strong>AutoLayout</strong>을 사용하였습니다. </li>
              <li> 앱의 완성도를 위해 <u>포기하지 않고 노력</u>했습니다. 블록이 연쇄적으로 더해지지 않는 상황에서 마감시간이 가까워져 마무리하려는 상황에서 고민을 더 하면 해결할 수 있다 판단하여 팀원들을 설득하였습니다. <strong>반복문의 종료 조건을 수정하여 연쇄 합성이 가능하도록 구현</strong>하였고, 결과적으로 완성도를 높일 수 있었습니다. </li>
              <li> 유사한 앱이 존재하여 <a href="https://developer.apple.com/kr/app-store/review/guidelines/" target="_blank">Design Spam</a> 사유로 앱 심사에서 배포가 거절되었습니다. 앱스토어의 유사 앱들과의 차별점을 두기 위해 <strong>Event Block</strong>을 구상하였습니다. Event Block에 따라 게임의 난이도가 달라지고, 이를 사용자가 선택하면 좋을 것 같다고 생각해 <strong>앱의 첫 화면에서 선택할 수 있도록 화면을 추가</strong>하였습니다. </li>
              <li> 앱의 목표 점수에 맞춰서 2048: Number Sliding으로 앱 이름을 지었고, 이에 맞춰 출시일을 4월 28일로 기획하고 앱 심사 신청과 승인을 마쳤습니다. 최종적으로 2024.04.28에 출시하여 현재는 피드백들을 수렴하여 앱 리팩토링 중에 있습니다. </li>
            </ul>
            </div>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:
        additional_links:
          - title:
            icon: fab fa-github
            url:
        sub_title:
        caption:
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            
            <br><br>
            
            **What I did**<br>
            
            <br><br>
            
            **Spec Sheet**<br>
            <mark></mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-2" aria-expanded="false" aria-controls="collapse-2" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-2">
            <ul>
              <li>  </li>
            </ul>
            </div>
                
      - layout: left
        title:
        additional_links:
          - title:
            icon: fab fa-github
            url:
        sub_title:
        caption:
        description: | # this will include new lines to allow paragraphs
            **Description**<br>
            
            <br><br>
            
            **What I did**<br>
            
            <br><br>
            
            **Spec Sheet**<br>
            <mark></mark>
            <br><br>

            <div data-toggle="collapse" data-target="#collapse-3" aria-expanded="false" aria-controls="collapse-3" style="cursor:pointer;">
            <p>
              <span class="glyphicon glyphicon-triangle-right" aria-hidden="true" style="font-size: 14px;"></span> <strong style="border-bottom: 1px solid black;">Retrospect</strong><br>
            </p>
            </div>
            <div class="collapse" id="collapse-3">
            <ul>
              <li>  </li>
            </ul>
            </div>
            
            
            
#  - title: Other # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title:
#        caption:
#        sub_title:
#        description: | # this will include new lines to allow paragraphs
            
    

# Footer
footer_show_references: false
# references_title:

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
